"""Embedded SOC: the five mandatory bricks. No telemetry or audit bypass allowed."""


class SOCCollector:
    def collect_event(self, event_type: str, payload: dict, correlation_id: str): ...
    def collect_log(self, level: str, message: str, context: dict): ...
    def collect_trace(self, span_name: str, attributes: dict): ...
    def collect_metric(self, name: str, value: float, labels: dict): ...


class SOCAnalyzer:
    def detect_anomaly(self, signal_type: str, threshold: float) -> list: ...
    def evaluate_risk(self, event_stream: list) -> dict: ...


class SOCDashboard:
    def health_status(self) -> dict: ...
    def risk_summary(self) -> dict: ...
    def incident_list(self, status: str = None) -> list: ...


class SOCForensics:
    def reconstruct_timeline(self, correlation_id: str) -> list: ...
    def audit_trail(self, entity_type: str, entity_id: str) -> list: ...


class SOCResponder:
    def block(self, target: str, reason: str) -> bool: ...
    def limit(self, target: str, rate: int) -> bool: ...
    def isolate(self, target: str) -> bool: ...
    def revoke(self, credential_id: str) -> bool: ...
    def rollback(self, deployment_id: str) -> bool: ...
    def escalate(self, incident_id: str, level: str) -> bool: ...
